languageCode:           "en"
title:                  "Noh Donggyeong's Portfolio"
baseURL:                "https://nohdonggyeong.github.io"
# baseURL:                "http://localhost:1313"
# baseURL:                "https://flowbite-admin-dashboard.vercel.app/"
enableInlineShortcodes: true
canonifyURLs: true

params:
  homepage: "https://nohdonggyeong.github.io"
  authors: Noh Donggyeong
  social_image_path: images/portfolio-bg.png

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
    style:              colorful
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishDir:             "_gh_pages"
