export const profile = {
  name: "노동경",
};

export type ProjectColor = "accent" | "purple" | "red" | "amber" | "blue" | "green"

export type Project = {
  id: string
  kind: "main" | "side"
  name: string
  org: string
  period: string
  summary: string | string[]
  detail: string | string[]
  contributions: string | string[]
  tags: string[]
  color: ProjectColor
  previewImage: string
  galleryImages?: string[]
  architectureImage?: string
  video?: string
  demoUrl?: string
}

export const mainProjects: Project[] = [
  {
    id: "fabrix",
    kind: "main",
    name: "삼성SDS - FabriX 개발 프로젝트",
    org: "에스코어",
    period: "2025.01. - 2025.12.",
    summary: ["AI 에이전트 플랫폼 스토어 서비스 백엔드 구축", "검색 성능 최적화 수행, '하이브리드 검색' 관련 기고"],
    detail: ["삼성SDS AI 풀스택 오퍼링 중 AI 플랫폼(FabriX) 내 에이전트 스토어 도메인의 서비스 개발·운영 고도화 과제"],
    contributions: [
      "AI 에이전트 스토어 백엔드 API 설계·구현, 컨테이너 기반 배포 환경 연동, 서비스 운영 이슈 대응 수행",
      "[하이브리드 검색 구조 적용 검토, 관련 기고](https://s-core.co.kr/insight/view/%EB%8D%94-%EC%A0%95%ED%99%95%ED%95%98%EA%B3%A0-%EC%9C%A0%EC%97%B0%ED%95%98%EA%B2%8C-%EC%B0%BE%EB%8A%94-%ED%95%98%EC%9D%B4%EB%B8%8C%EB%A6%AC%EB%93%9C-%EA%B2%80%EC%83%89-llm%EC%9D%98-%ED%99%95/)",
    ],
    tags: ["FastAPI", "Python", "SQLAlchemy", "PostgreSQL", "Kubernetes", "ArgoCD", "Jenkins", "Helm"],
    color: "accent",
    previewImage: "/images/joined-project/fabrixv2_01.png",
    galleryImages: ["/images/joined-project/fabrixv2_01.png", "/images/joined-project/fabrixv2_03.png"],
    architectureImage: "/images/joined-project/fabrixv2_02.png",
  },
  {
    id: "gravix",
    kind: "main",
    name: "삼성SDS - GraviX 개발 프로젝트",
    org: "에스코어",
    period: "2023.04. - 2024.12.",
    summary: ["멀티 테넌트 카탈로그 서비스 백엔드 설계·구현", "코드 품질 개선 및 보안 취약점 대응 체계 운영"],
    detail: ["기업 내 데이터·소프트웨어·애플리케이션 자산의 통합 관리와 탐색 효율 개선을 목표로 한 카탈로그 플랫폼(현, FabriX) 개발 과제"],
    contributions: ["MSA 기반 백엔드 기능 개발, 검색 엔진 운영, 정적 분석 기반 품질 개선, 보안 점검 대응, 성능 모니터링 및 배포 운영 수행"],
    tags: ["Java", "Spring Boot", "JPA", "QueryDSL", "PostgreSQL", "Elasticsearch", "Kubernetes", "Jenkins", "Helm", "Maven", "Flyway", "Pinpoint", "SonarQube", "BurpSuite", "Python"],
    color: "accent",
    previewImage: "/images/joined-project/fabrix2.png",
    galleryImages: ["/images/joined-project/fabrix2.png", "/images/joined-project/fabrix3.png"],
    architectureImage: "/images/joined-project/fabrix4.png",
  },
  {
    id: "nia-2022-error-correction",
    kind: "main",
    name: "NIA - 2022 AI 학습용 데이터 구축 지원사업",
    org: "솔트룩스이노베이션",
    period: "2022.06. - 2022.12.",
    summary: ["자판·음성 I/F 오류 교정 데이터 수집 플랫폼 구축", "데이터 집계·검증 중심의 관리자 기능 구현"],
    detail: ["PC/모바일 입력 환경에서 발생하는 오타 문장 수집 및 품질 검수를 위한 저작·관리 도구 개발 과제"],
    contributions: ["관리자 및 검수 화면 설계·구현, 운영 단계 유지보수 수행"],
    tags: ["Java", "Spring Boot", "MyBatis", "Cubrid", "Vue.js", "Maven", "Jenkins"],
    color: "accent",
    previewImage: "/images/joined-project/errorcorrection3.png",
    galleryImages: ["/images/joined-project/errorcorrection3.png", "/images/joined-project/errorcorrection2.png"],
    architectureImage: "/images/joined-project/errorcorrection4.png",
  },
  {
    id: "aica-2021-prototype",
    kind: "main",
    name: "AICA - 2021 AI (시)제품 제작 지원사업",
    org: "솔트룩스이노베이션",
    period: "2021.09. - 2021.12.",
    summary: ["비대면 크라우드소싱 서비스 플랫폼 구축", "회원·비용 관리 중심의 운영자 기능 구현"],
    detail: ["회원, 데이터, 저작도구, AI 모델, 비용 항목을 통합 관리하는 크라우드소싱 플랫폼 개발 과제"],
    contributions: ["관리자 기능(회원 관리, 비용 관리 등) 설계·구현 수행"],
    tags: ["Java", "eGovFramework", "Thymeleaf", "MariaDB", "Apache Tomcat", "Docker-compose"],
    color: "accent",
    previewImage: "/images/joined-project/prototype21_1.PNG",
    galleryImages: ["/images/joined-project/prototype21_1.PNG", "/images/joined-project/prototype21_2.JPG"],
    architectureImage: "/images/joined-project/prototype21_3.png",
  },
  {
    id: "nia-2021-vehicle",
    kind: "main",
    name: "NIA - 2021 AI 학습용 데이터 구축 지원사업",
    org: "솔트룩스이노베이션",
    period: "2021.05. - 2021.12.",
    summary: ["차량 내·외부 상황 인식 데이터 수집 플랫폼 구축", "수집·라벨링·검증 E2E 프로세스 구현"],
    detail: ["운전자 제스처 인식 모델 학습을 위한 영상 데이터 수집·저작·검수 체계 구축 과제"],
    contributions: ["저작도구 설계, 핵심 기능 구현, 운영 유지보수 전 과정 수행"],
    tags: ["Python", "Django", "Javascript", "MariaDB", "MediaPipe Hands", "Nginx", "Gunicorn", "Docker-compose"],
    color: "accent",
    previewImage: "/images/joined-project/vehicle5.png",
    galleryImages: ["/images/joined-project/vehicle5.png", "/images/joined-project/vehicle3.png"],
    architectureImage: "/images/joined-project/vehicle6.png",
  },
  {
    id: "aica-2020-digital-human",
    kind: "main",
    name: "AICA - 2020 AI (시)제품 제작 지원사업",
    org: "솔트룩스이노베이션",
    period: "2020.09. - 2020.12.",
    summary: ["심층 질의응답 기반 디지털 휴먼 서비스 개발", "TTS 모델 고도화 및 운영 체계 구축"],
    detail: ["STT·TTS·NLP·객체 인식 모델을 연계한 디지털 휴먼 대화 서비스 개발 과제"],
    contributions: ["운영 서버 관리, 솔루션 운영, Tacotron2 기반 TTS 고도화, 음성 분할·편집 자동화 모듈 구현 수행"],
    tags: ["Python", "TTS(Tacotron2)", "STT", "CentOS", "Ubuntu"],
    color: "accent",
    previewImage: "/images/joined-project/prototype20_4.jpg",
    galleryImages: ["/images/joined-project/prototype20_4.jpg", "/images/joined-project/prototype20_5.jpg"],
    architectureImage: "/images/joined-project/prototype20_3.png",
  },
  {
    id: "nia-2020-clinomics",
    kind: "main",
    name: "NIA - 2020 AI 학습용 데이터 구축 지원사업",
    org: "솔트룩스이노베이션",
    period: "2020.09. - 2020.12.",
    summary: ["폐암 예후 예측 AI 데이터 수집 플랫폼 개발", "영상·라벨링 중심 데이터 처리 기능 구현"],
    detail: ["PET/CT 영상과 임상·유전자 정보를 기반으로 한 예후 예측 모델 학습 데이터 수집·관리 도구 구축 과제"],
    contributions: ["프론트엔드 핵심 기능(이미지 로드, 드래그, 확대·축소·회전, 라벨링) 설계·구현 수행"],
    tags: ["Python", "Django", "Javascript", "PostgreSQL", "Nginx", "Gunicorn", "Docker-compose"],
    color: "accent",
    previewImage: "/images/joined-project/clinomics2.PNG",
    galleryImages: ["/images/joined-project/clinomics2.PNG", "/images/joined-project/clinomics3.PNG"],
    architectureImage: "/images/joined-project/clinomics1.png",
  },
]

export const sideProjects: Project[] = [
  {
    id: "voice-collector",
    kind: "side",
    name: "TTS 학습용 음성데이터 수집 도구",
    org: "개인",
    period: "2022.12. - 2023.01.",
    summary: ["권한 분리 기반 음성 수집·검수 라벨링 도구 개발"],
    detail: ["TTS 모델 학습 데이터 확보를 위한 크라우드형 음성 수집·검수 서비스 개발 과제"],
    contributions: ["대본 등록, 녹음 워크플로, 검수 프로세스, 회원 관리 기능 설계·구현 수행"],
    tags: ["Docker-compose", "Spring Boot", "JPA", "MariaDB", "Spring Security", "Thymeleaf", "Javascript", "FFMPEG"],
    color: "accent",
    previewImage: "/images/side-project/voicecollector1.PNG",
    galleryImages: ["/images/side-project/voicecollector1.PNG", "/images/side-project/voicecollector3.PNG"],
    video: "/videos/voicecollector.mp4",
  },
  {
    id: "nicework-hr-platform",
    kind: "side",
    name: "팀 HR관리 그룹웨어 플랫폼",
    org: "개인",
    period: "2022.01. - 2022.02.",
    summary: ["계약직 인력 대상 연장근로·연차 그룹웨어 개발"],
    detail: ["엑셀 중심 HR 관리 업무를 웹 기반 프로세스로 전환하기 위한 팀 단위 운영 플랫폼 개발 과제"],
    contributions: ["일일 업무 기록, 연장근로·휴가 신청, 캘린더 조회, 인증·인가, 문서 다운로드 기능 구현"],
    tags: ["Docker-compose", "Django", "Nginx", "Gunicorn", "PostgreSQL"],
    color: "accent",
    previewImage: "/images/side-project/nicework.png",
    galleryImages: ["/images/side-project/nicework.png", "/images/side-project/nicework2.png"],
    video: "/videos/nicework.mp4",
  },
  {
    id: "recreation-quiz",
    kind: "side",
    name: "레크레이션 인물 퀴즈 앱",
    org: "개인",
    period: "2021.09. - 2021.10.",
    summary: ["통합 워크샵 운영용 인물 퀴즈 애플리케이션 개발"],
    detail: ["사내 워크샵 레크레이션 진행을 위한 참여형 퀴즈 앱 제작 과제"],
    contributions: ["PyQt 기반 GUI 구성 및 PyInstaller 기반 실행 파일 배포 패키지 제작 수행"],
    tags: ["Python", "PyQt", "PyInstaller"],
    color: "accent",
    previewImage: "/images/side-project/recreation1.png",
    galleryImages: ["/images/side-project/recreation1.png", "/images/side-project/recreation2.png"],
    video: "/videos/recreation.mp4",
  },
  {
    id: "equipment-management",
    kind: "side",
    name: "회사 장비 관리 플랫폼",
    org: "개인",
    period: "2021.06. - 2021.07.",
    summary: ["사내 장비 수량·사용 현황 관리 서비스 개발"],
    detail: ["엑셀 기반 장비 관리의 동기화 한계를 해소하기 위한 웹 기반 관리 서비스 구축 과제"],
    contributions: ["장비 등록·삭제·조회, 사용자별 사용 현황 조회 기능 설계·구현 수행"],
    tags: ["Docker-compose", "Django", "Nginx", "Gunicorn", "MariaDB"],
    color: "accent",
    previewImage: "/images/side-project/eqpmngt1.PNG",
    galleryImages: ["/images/side-project/eqpmngt1.PNG", "/images/side-project/eqpmngt2.png"],
    video: "/videos/eqpmngt.mp4",
  },
  {
    id: "say-list",
    kind: "side",
    name: "Say List",
    org: "개인",
    period: "2020.05. - 2020.06.",
    summary: ["Google STT 기반 일정·메모 안드로이드 앱 개발"],
    detail: ["음성 입력을 통해 일정 및 메모를 등록·관리할 수 있는 모바일 애플리케이션 개발 과제"],
    contributions: ["Google SpeechRecognizer 연동, SQLite 데이터 관리, 일정 수정·삭제 기능 구현 수행"],
    tags: ["Android", "Google STT", "SQLite"],
    color: "accent",
    previewImage: "/images/side-project/sayList.jpg",
    galleryImages: ["/images/side-project/sayList.jpg", "/images/side-project/voiceMemo.jpg"],
    video: "/videos/saylist.mp4",
  },
  {
    id: "first-web-portfolio",
    kind: "side",
    name: "My First Web Portfolio",
    org: "개인",
    period: "2020.06. - 2020.06.",
    summary: ["IT 직무 지원용 개인 웹 포트폴리오 구축"],
    detail: ["초기 커리어 역량과 프로젝트 경험을 구조화해 제시하는 정적 웹 포트폴리오 제작 과제"],
    contributions: ["콘텐츠 기획, 화면 레이아웃 설계, 프로젝트 소개 구조 및 UI 구현 수행"],
    tags: ["HTML", "CSS", "Javascript"],
    color: "accent",
    previewImage: "/images/side-project/portfolio_ver1_img.PNG",
    galleryImages: ["/images/side-project/portfolio_ver1_img.PNG"],
    demoUrl: "/portfolio_ver1.html",
  },
]
